name: CI

on:
  pull_request:
    paths-ignore: ["*.md"]
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 15.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node@${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Run tests
        run: yarn ci:test
      - name: Check bundle size
        run: yarn size:check
      - name: Report code coverage
        run: yarn ci:report
